apiVersion: v2
name: doda-app
description: Helm chart for the app-service and model-service
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: "79.9.0"       
    repository: "https://prometheus-community.github.io/helm-charts"
    alias: monitoring
    condition: monitoring.enabled