# App Service (exposed externally)
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service  
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: app-service
  ports:
    - name: http
      port: {{ .Values.app.service.port }}     # external port
      targetPort: {{ .Values.app.env.serverPort }}    # container port (SERVER_PORT)
