{{- if and .Values.istio.enabled .Values.istio.globalRateLimit.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-global-ratelimit-actions
  namespace: {{ .Values.istio.globalRateLimit.istioNamespace | default "istio-system" | quote }}
spec:
  workloadSelector:
    labels:
      {{ .Values.istio.ingressGateway.selectorLabelKey }}: {{ .Values.istio.ingressGateway.selectorLabelValue | quote }}
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: ""
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        rate_limits:
        - actions:
          - request_headers:
              header_name: "x-user-id"
              descriptor_key: "USER"
{{- end }}
