{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-destinationrule
spec:
  host: app-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: {{ .Values.istio.canary.cookieName | quote }}
          ttl: {{ .Values.istio.canary.cookieTtl | quote }}

  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
{{- end }}
