{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
spec:
  selector:
    {{ .Values.istio.ingressGateway.selectorLabelKey }}: {{ .Values.istio.ingressGateway.selectorLabelValue | quote }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.hosts.stable | quote }}
        - {{ .Values.istio.hosts.preview | quote }}
{{- end }}
