apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  labels:
    app: app-service
    release: {{ .Release.Name }}     
spec:
  selector:
    matchLabels:
      app: app-service         
  endpoints:
    - port: http               
      path: /metrics           
      interval: {{ .Values.app.service.monitoring.interval }}
