apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  labels:
    app: app-service
    release: monitoring        
spec:
  selector:
    matchLabels:
      app: app-service         
  endpoints:
    - port: http               
      path: /metrics           
      interval: 10s
